### ISSUE TITLE
web demo 提示 CAN_NOT_GET_GATEWAY_SERVER  错误

### ISSUE THREAD

**Issue by crmlei** [AgoraIO/API-Examples-Web#69]
请问下这个错误：

运行 basicVideoCall/index.html后，填入appid,token,channel后，点击join无反应，查询浏览器控制台显示以下的错误：

14:55:14:88 Agora-SDK [ERROR]: [client-f541a] join number: 1, Joining channel failed, rollback AgoraRTCException: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: flag: 4096, message: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: invalid vendor key, can not find appid
    at vO (https://download.agora.io/sdk/release/AgoraRTC_N.js:6:15168)
    at TO.e.gatewayInfo.IT.joinChooseServer.lts (https://download.agora.io/sdk/release/AgoraRTC_N.js:6:12767)
    at async https://download.agora.io/sdk/release/AgoraRTC_N.js:5:123411

前面页面初始化media device 是正常的。

尝试下 Edge和Chrome都是相同的错误。

**Comment by crmlei** [comment]
抱歉，准备重新写一个，刚才测试是随意输入了 appid和token
